# Generated by Django 4.0.6 on 2022-08-09 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['pk']},
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
        migrations.AddField(
            model_name='product',
            name='image_url1',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image_url2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image_url3',
            field=models.URLField(blank=True, null=True),
        ),
    ]
