# Generated by Django 4.0.6 on 2022-08-09 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_order_options_alter_orderitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_url1',
            field=models.ImageField(blank=True, null=True, upload_to=None),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url2',
            field=models.ImageField(blank=True, null=True, upload_to=None),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url3',
            field=models.ImageField(blank=True, null=True, upload_to=None),
        ),
    ]
